# Generated by Django 3.2.3 on 2021-06-06 09:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210606_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blgpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
