# Generated by Django 3.2.3 on 2021-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blgpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blgpost',
            name='category',
            field=models.CharField(default="Freakin' Blog!", max_length=255),
        ),
    ]
