# Generated by Django 3.2.3 on 2021-06-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blgpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blgpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blgcategory'),
        ),
    ]
