# Generated by Django 3.2.3 on 2021-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blgpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blgpost',
            name='snippet',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blgpost',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
